apiVersion: v1
kind: BuildConfig
metadata:
  name: nodeapp-pipeline
  labels:
    name: nodeapp-pipeline
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "nodejs-app", "namespace": "development", "kind": "DeploymentConfig"}]'
spec:
  triggers:
    -
      type: GitHub
      github:
        secret: secret101
    -
      type: Generic
      generic:
        secret: secret101
  runPolicy: Serial
  source:
    type: None
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: "node() {\nstage 'build'\nopenshiftBuild(namespace: 'development',buildConfig: 'nodejs-app',   showBuildLogs: 'true')\nstage 'deploy'\nopenshiftDeploy(namespace: 'development',deploymentConfig: 'nodejs-app')\nopenshiftScale(namespace: 'development',deploymentConfig: 'nodejs-app',replicaCount: '2')\n}"
  output:
  resources:
  postCommit:
